<a href="https://colab.research.google.com/github/chaitanysaraswat/Advanced-Analytics-Using-Statistics/blob/main/lecture2_numpy19_05_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
a1=np.array([3,7,6,1,8,9])
a2=np.array([2,4,58,10,3,6])

in probability whenever there is and it intersection and values need to be mutiplyied.
whenever it is or it union  its values need to be added.

whenever someone ask union either in one set or in another.
whenever someone ask intersection are present in both

In [8]:
np.intersect1d(a1,a2)

array([3, 6])

In [6]:
np.union1d(a1,a2)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 58])

In [11]:
# diff will give element that are present in a1 but not in a2 or we can say unique to a1 only
np.setdiff1d(a1,a2)

array([1, 7, 8, 9])

In [ ]:
# diff will give element that are presenet in a2 but not in a1 or we can say unique to a1
np.setdiff1d(a2,a1)

In [12]:
# xorld is xor gate  which will give unique of a1 and unique of a2 ////
np.setxor1d(a1,a2)

array([ 1,  2,  4,  7,  8,  9, 10, 58])

In [13]:
np.isin(a1,a2) # will give whether a1 value prsent a2 or not it will give true else false


array([ True, False,  True, False, False, False])

In [14]:
np.where(np.isin(a1,a2))

(array([0, 2]),)

for matrix mutlication no of rows of a matrix is equal to no of column of b

In [18]:
x1=np.array([2,3,-4])
x2=np.array([3,-2,1])

In [19]:
np.dot(x1,x2) #dot product of two vectors x1 and x2

np.int64(-4)