<a href="https://colab.research.google.com/github/chaitanysaraswat/Advanced-Analytics-Using-Statistics/blob/main/Lecture1_numpy18_05_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Interview 3 types of question :
# 1 basic question(banana peel question if you dont know u will not go further)
# 2 performance question
# 3 tiger question(tie breaker)

# *Lecture 1(numpy)

In [1]:
import numpy as np
import pandas as pd

In [2]:
# numpy uses nd array as default
x1=[4,8,7,6,9]
type(x1)

list

In [5]:
a1=np.array(x1)
a1


array([4, 8, 7, 6, 9])

In [6]:
type(a1)


numpy.ndarray

In [7]:
#second list
x2=[6,9,1,3,2]
x2

[6, 9, 1, 3, 2]

In [9]:
# creating 2 dimensional array
a2=np.array([x1,x2]) # you cand add multiple values using []
a2

array([[4, 8, 7, 6, 9],
       [6, 9, 1, 3, 2]])

In [11]:
x1=list(range(11))
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
a1=np.arange(11) # arange will make list into array
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a1=np.arange(3,14) # starting at 3 and ending at 13
a1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [17]:
a1=np.arange(24,4,-1) # last element will be 5 (last element+1)
print(a1)

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]


In [20]:
a1=np.arange(3,90,3) # it will stop before 90 whether steps can be printed
a1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

In [23]:
#number of values to be printed can't be in decimal in linspace but in arange() its steps
x1=np.linspace(2,5,10) # linspace is going to create ten values including 2(start) and 5(end) and space will be decided by python
x1

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [24]:
x1=np.linspace(2,5,10,endpoint=False) # linspace is going to create ten values including 2(start) and will not include 5(end) and space will be decided by python
x1

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7])

In [25]:
a1=np.arange(3,14)

In [27]:
np.append(a1,3)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  3])

In [28]:
a1 # element doesn't add

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
a1=np.append(a1,3)
a1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  3,  3])

In [31]:
a2=np.array([2,9,8])

In [32]:
a3=np.concatenate((a1,a2))
a3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  3,  3,  2,  9,  8])

In [33]:
a1


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  3,  3])

In [34]:
a2=np.insert(a1,3,9) # value 9 is added at index of 3
a2

array([ 3,  4,  5,  9,  6,  7,  8,  9, 10, 11, 12, 13,  3,  3])

In [35]:
np.delete(a2,3) #it will not show  value at index  3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  3,  3])

In [36]:
a2 # a2 is same

array([ 3,  4,  5,  9,  6,  7,  8,  9, 10, 11, 12, 13,  3,  3])

In [37]:
a1=np.array([3,4,5,6,9,8,7,6])
len(a1)

8

In [53]:
# first value will be row and second will be column
a3=a1.reshape(4,2)# reshape will make this into 4 rows 2 columns
a3

array([[3, 4],
       [5, 6],
       [9, 8],
       [7, 6]])

In [45]:
a3=a1.reshape(2,4)
a3
a3=a1.reshape(8,1)# count number of to find out dimnension of array know count []
a3

array([[3],
       [4],
       [5],
       [6],
       [9],
       [8],
       [7],
       [6]])

In [90]:
a4=a1.reshape(-1,2) # means -1 (row) leave to u for python to decide and 2nd number of columns we want

array([[3, 4],
       [5, 6],
       [9, 8],
       [7, 6]])

In [91]:
a4=a1.reshape(-1,) # we to specify atleast row column uu dont give ok
a4

array([3, 4, 5, 6, 9, 8, 7, 6])

In [54]:
a3[3]

array([7, 6])

In [55]:
a3[2,:]#takes 2nd row(index 1) and all column
a3[:,1]#takes all row and 1st column(index 0)

array([4, 6, 8, 6])

In [56]:
a3[[2,3],:] #taking row 2nd and 3rd(index at 1 and 2 bcoz indext atart at 0)
a3[:,[0,1]]

array([[3, 4],
       [5, 6],
       [9, 8],
       [7, 6]])

In [58]:
newcol=np.array([3,7,1,9])
newcol=newcol.reshape(-1,1)
newcol

array([[3],
       [7],
       [1],
       [9]])

In [62]:
a4=np.hstack([a3,newcol]) # if we want to add column 1> create array 2>reshape it in (-1,1) transpose format 3>then hstack it we are using
a4

array([[3, 4, 3],
       [5, 6, 7],
       [9, 8, 1],
       [7, 6, 9]])

In [64]:
newrow =np.array([2,4,5])# number_of_values = existing_columns
a5=np.vstack([a4,newrow])
a5

array([[3, 4, 3],
       [5, 6, 7],
       [9, 8, 1],
       [7, 6, 9],
       [2, 4, 5]])

In [83]:
a4=np.insert(a4,3,[10,14,4],axis=0)#in insertion a4 into which insert happens 3 index where array need to be inserted axis=0 for rows and axis 1 for column
a4

array([[ 3,  4,  3],
       [ 5,  6,  7],
       [ 7,  6,  9],
       [10, 14,  4],
       [10, 14,  4]])

In [86]:
a4=np.insert(a4,2,[12,14,7,31,42],axis=1)
a4

array([[ 3,  4, 12,  1, 11,  3],
       [ 5,  6, 14, 14, 14,  7],
       [ 7,  6,  7,  7,  7,  9],
       [10, 14, 31,  3,  3,  4],
       [10, 14, 42,  4,  4,  4]])

In [87]:
a4=np.delete(a4,2,axis=0)
a4

array([[ 3,  4, 12,  1, 11,  3],
       [ 5,  6, 14, 14, 14,  7],
       [10, 14, 31,  3,  3,  4],
       [10, 14, 42,  4,  4,  4]])

# Brodcasting
broadcasting makes  it possible to repeat the same operation accross all values.

In [97]:
a1=np.array([4,7,6,8,9])
a2=np.array([4,2,7,6,3])

In [99]:
a1 + 5

array([ 9, 12, 11, 13, 14])

In [100]:
2*a1+5

array([13, 19, 17, 21, 23])

In [103]:
a1+a2# in this array item to item addition take place and in list concat happens and recycling doesn't happen like in r language

array([ 8,  9, 13, 14, 12])

In [104]:
a1=np.array([2,4,5,6,7,9,3,1,2,6,7,9])
len (a1)

12

In [105]:
a2=a1.reshape(3,4)
a2

array([[2, 4, 5, 6],
       [7, 9, 3, 1],
       [2, 6, 7, 9]])

In [107]:
a3=np.array([2,4,6,8])


In [108]:
a2+a3 #adds every single list element of every dimensional element row-wise

array([[ 4,  8, 11, 14],
       [ 9, 13,  9,  9],
       [ 4, 10, 13, 17]])

In [115]:
a3=np.array([3,4,5])
a3=a3.reshape(-1,1)
a3

array([[3],
       [4],
       [5]])

In [116]:
a2

array([[2, 4, 5, 6],
       [7, 9, 3, 1],
       [2, 6, 7, 9]])

In [117]:
a2+a3

array([[ 5,  7,  8,  9],
       [11, 13,  7,  5],
       [ 7, 11, 12, 14]])

In [123]:
a1


array([[7, 9, 3, 1],
       [2, 6, 7, 9]])

In [ ]:
t

# where are values greater than 4
# how many values are greater than 4
# what are the value which are greater than 4

In [135]:
a1

array([2, 4, 5, 6, 7, 9, 3, 1, 2, 6, 7, 9])

In [127]:
ind=np.where(a1>4) #input to np.where cmd is the condn need to be checked output of np.where cmd are the indices where the condition is true
ind

(array([ 2,  3,  4,  5,  9, 10, 11]),)

In [137]:
len(ind[0])
(a1>4).sum() #u can use it without np.where

np.int64(7)

In [131]:
a1[ind]

array([5, 6, 7, 9, 6, 7, 9])

In [132]:
x1 = (np.arange(48)).reshape(6,8)   # creates a 2d array of 6 rows and 8 columns
x2 = np.resize(x1,(12,4))   #  resizes the array x1 which was having 6 rows and 8 cols to an array with 12 rows and 4 cols

x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays
# are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally
x4 = np.split(x1,[2,3,5], axis=1)    # splitting happens vertically


b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
c = sorted(b)          #sorts the array in increasing order
c = sorted(b)[::-1]    # sorts the array in the decreasing order
np.sort(b)     # also PRINTS the array in the increasing order, original array is unchanged

b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 columns
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

array([[1, 2, 4, 7],
       [5, 6, 8, 9],
       [1, 2, 3, 5]])