<a href="https://colab.research.google.com/github/chaitanysaraswat/Advanced-Analytics-Using-Statistics/blob/main/NumpyAssignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#1. Write a NumPy program to find the dot product of two arrays of different dimensions.
import numpy as np
x1=np.array([[2,5,6],[2,3,7]])
x2=np.array([3,7,8])

In [7]:
print(np.dot(x1,x2))


[89 83]


In [13]:
# 2. Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.
x1=np.array([[2,5,6],[3,7,8],[8,23,56]])
x1
x1=np.identity(3)
print(x1)
print(np.vstack((x1,x1)),end='\n\n')
print(np.hstack((x1,x1)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]


In [24]:
# 3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.
import random
x1=np.random.randint(1,50,16)
print(np.array(x1).reshape(4,4),end='\n\n')
np.array(x1).reshape(4,4).sum(axis=1)

[[32 16 30 17]
 [18  5 15  3]
 [38 17 20 29]
 [45  3 49 42]]



array([ 95,  41, 104, 139])

In [37]:
# 4. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.
import random
x1=np.random.randint(1,50,9)
m=np.array(x1).reshape(3,3)
mean=np.array(x1).reshape(3,3).mean(axis=1)
print(mean-m)


[[ -2.  -1.  29.]
 [ -1.   0.  18.]
 [-24. -16.  -3.]]


In [8]:
# 5. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.
x1=np.random.randint(1,50,9).reshape(3,3)
mean=x1.mean(axis=0)
print(x1-mean)


[[ -5.          27.66666667  12.        ]
 [ 13.         -13.33333333   0.        ]
 [ -8.         -14.33333333 -12.        ]]


In [13]:
# 6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.
x1=np.random.randint(1,50,25).reshape(5,5)
arr_sum= x1.sum(axis=1)
normalized=arr_sum-x1
normalized


array([[147,  80,  51,  99, 107],
       [151,  79,  45, 110, 140],
       [141, 112,  69,  94, 147],
       [156,  96,  83,  86, 113],
       [117,  85,  79,  86, 127]])

In [14]:
# 7. Write a NumPy program to create a 5x5 array with random values and normalize it column-wise.
x1=np.random.randint(1,50,25).reshape(5,5)
arr_sum= x1.sum(axis=0)
normalized=arr_sum-x1
normalized

array([[ 65,  98, 133,  38, 112],
       [ 89, 113, 103,  50, 141],
       [ 65,  93, 101,  55, 122],
       [ 93,  80, 129,  44, 107],
       [ 76,  72,  90,  49, 134]])

In [22]:
import numpy as np

arr = np.array([[[1, 2, 3],
                [4, 5, 6]],[1,2,3]])

# Sums along the last axis (columns) to give row totals
result = np.sum(arr, axis=-1)
result
# Output: [6, 15]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [29]:
# 8. Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.
x1=np.random.random((3,3,3))
np.sum(x1,axis=-1)


array([[1.49451622, 1.20708006, 1.01653883],
       [1.92494371, 1.02725879, 1.36496274],
       [1.84413936, 1.17677791, 2.24428571]])

In [33]:
# 9. Write a NumPy program to create a 5x5 array with random values and sort each row.

x1=np.random.random((5,5))
print(x1,end='\n\n')
print(np.sort(x1,axis=1))

[[0.38022443 0.17825122 0.43999964 0.20506466 0.5942106 ]
 [0.18681045 0.14033629 0.88418189 0.14700875 0.43593944]
 [0.62389467 0.90528083 0.50755451 0.24609293 0.41975735]
 [0.8061619  0.7015229  0.53291904 0.94877361 0.28369409]
 [0.09431477 0.97114032 0.43590157 0.26517121 0.84293717]]

[[0.17825122 0.20506466 0.38022443 0.43999964 0.5942106 ]
 [0.14033629 0.14700875 0.18681045 0.43593944 0.88418189]
 [0.24609293 0.41975735 0.50755451 0.62389467 0.90528083]
 [0.28369409 0.53291904 0.7015229  0.8061619  0.94877361]
 [0.09431477 0.26517121 0.43590157 0.84293717 0.97114032]]


In [34]:
# 10. Write a NumPy program to create a 5x5 array with random values and sort each column.

x1=np.random.random((5,5))
print(x1,end='\n\n')
print(np.sort(x1,axis=0))

[[0.45901789 0.54399915 0.26876273 0.41624626 0.67781028]
 [0.80726203 0.99070088 0.98657885 0.07524546 0.44260348]
 [0.82961146 0.36161052 0.44891731 0.5617948  0.64030331]
 [0.60153926 0.98045187 0.07946031 0.98066071 0.65605718]
 [0.92875668 0.94131115 0.14451994 0.80038395 0.33012703]]

[[0.45901789 0.36161052 0.07946031 0.07524546 0.33012703]
 [0.60153926 0.54399915 0.14451994 0.41624626 0.44260348]
 [0.80726203 0.94131115 0.26876273 0.5617948  0.64030331]
 [0.82961146 0.98045187 0.44891731 0.80038395 0.65605718]
 [0.92875668 0.99070088 0.98657885 0.98066071 0.67781028]]


In [40]:
# 11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.
x1=np.random.random((5,5))
print(x1,end='\n\n')
z=np.sort(x1,axis=1)
print(z)
z[:,3]

[[0.23892458 0.46582173 0.03331891 0.098345   0.0731051 ]
 [0.26291668 0.03474644 0.64354005 0.37604092 0.19618261]
 [0.19502458 0.00966282 0.42507047 0.77715256 0.02065167]
 [0.72102364 0.95248089 0.04637906 0.47656369 0.87614418]
 [0.20659839 0.10569421 0.79499668 0.26889108 0.65111922]]

[[0.03331891 0.0731051  0.098345   0.23892458 0.46582173]
 [0.03474644 0.19618261 0.26291668 0.37604092 0.64354005]
 [0.00966282 0.02065167 0.19502458 0.42507047 0.77715256]
 [0.04637906 0.47656369 0.72102364 0.87614418 0.95248089]
 [0.10569421 0.20659839 0.26889108 0.65111922 0.79499668]]


array([0.23892458, 0.37604092, 0.42507047, 0.87614418, 0.65111922])

In [41]:
# 12. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.
x1=np.random.random((5,5))
print(x1,end='\n\n')
z=np.sort(x1,axis=0)
print(z)
z[:,3]

[[0.07584544 0.80955816 0.65664463 0.85414185 0.51012889]
 [0.01207819 0.36500985 0.29511556 0.66900754 0.35162699]
 [0.64997122 0.72643503 0.52186727 0.24813325 0.66299759]
 [0.48528258 0.55868985 0.92932588 0.47789802 0.22428764]
 [0.64607599 0.41651236 0.73878478 0.57039069 0.22289461]]

[[0.01207819 0.36500985 0.29511556 0.24813325 0.22289461]
 [0.07584544 0.41651236 0.52186727 0.47789802 0.22428764]
 [0.48528258 0.55868985 0.65664463 0.57039069 0.35162699]
 [0.64607599 0.72643503 0.73878478 0.66900754 0.51012889]
 [0.64997122 0.80955816 0.92932588 0.85414185 0.66299759]]


array([0.24813325, 0.47789802, 0.57039069, 0.66900754, 0.85414185])

In [ ]:
# 13. Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.
